kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  # A deployment's specification really only 
  # has a few useful options

  # 1. How many copies of each pod do we want?
  replicas: 1
  selector:
    matchLabels:
      app: nginx

  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
          - containerPort: 80
